20200217 11:57:48 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:31  
Auth server [tcp] listen at: 	8000
20200217 11:57:48 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:37  
register Auth Service:[1] service success
20200217 11:57:48 Debug../../apps/lua_test/scripts/datebase/mysql_auth_center.lua:19  
connect to auth_center_db success
20200217 11:58:05 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:28  
new client come [127.0.0.1:60562]
20200217 11:58:22 DebugF:\Projects\unity\Moba\Server\netbus\Netbus.cpp:238  
client command!!
20200217 11:58:22 DebugF:\Projects\unity\Moba\Server\netbus\protocol\CmdPackageProtocol.cpp:175  
获取Message类型为空：
20200217 11:58:22 Debug../../apps/lua_test/scripts/auth/AuthService.lua:20  
client [127.0.0.1:60562] leave
20200217 12:11:16 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:31  
Auth server [tcp] listen at: 	8000
20200217 12:12:11 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:31  
Auth server [tcp] listen at: 	8000
20200217 12:12:11 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:37  
register Auth Service:[1] service success
20200217 12:12:11 Debug../../apps/lua_test/scripts/datebase/mysql_auth_center.lua:19  
connect to auth_center_db success
20200217 12:12:11 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:28  
new client come [127.0.0.1:60988]
20200217 12:12:26 Debug../../apps/lua_test/scripts/auth/AuthService.lua:20  
client [127.0.0.1:60988] leave
20200217 12:12:56 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:31  
Auth server [tcp] listen at: 	8000
20200217 12:12:56 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:37  
register Auth Service:[1] service success
20200217 12:12:56 Debug../../apps/lua_test/scripts/datebase/mysql_auth_center.lua:19  
connect to auth_center_db success
20200217 12:13:25 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:28  
new client come [127.0.0.1:61016]
20200217 12:13:43 DebugF:\Projects\unity\Moba\Server\netbus\Netbus.cpp:238  
client command!!
20200217 12:13:43 DebugF:\Projects\unity\Moba\Server\netbus\protocol\CmdPackageProtocol.cpp:175  
获取Message类型为空：
20200217 12:13:43 Debug../../apps/lua_test/scripts/auth/AuthService.lua:20  
client [127.0.0.1:61016] leave
20200217 12:49:53 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:31  
Auth server [tcp] listen at: 	8000
20200217 12:49:53 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:37  
register Auth Service:[1] service success
20200217 12:49:53 Debug../../apps/lua_test/scripts/datebase/mysql_auth_center.lua:19  
connect to auth_center_db success
20200217 12:51:33 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:28  
new client come [127.0.0.1:61587]
20200217 12:51:57 DebugF:\Projects\unity\Moba\Server\netbus\Netbus.cpp:238  
client command!!
20200217 12:51:57 DebugF:\Projects\unity\Moba\Server\netbus\protocol\CmdPackageProtocol.cpp:175  
获取Message类型为空：
20200217 12:51:57 Debug../../apps/lua_test/scripts/auth/AuthService.lua:20  
client [127.0.0.1:61587] leave
20200217 12:57:08 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:31  
Auth server [tcp] listen at: 	8000
20200217 12:57:08 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:37  
register Auth Service:[1] service success
20200217 12:57:08 Debug../../apps/lua_test/scripts/datebase/mysql_auth_center.lua:19  
connect to auth_center_db success
20200217 12:57:20 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:28  
new client come [127.0.0.1:61706]
20200217 12:57:42 DebugF:\Projects\unity\Moba\Server\netbus\Netbus.cpp:237  
client command!!
20200217 12:57:42 DebugF:\Projects\unity\Moba\Server\netbus\protocol\CmdPackageProtocol.cpp:175  
获取Message类型为空：
20200217 12:57:42 Debug../../apps/lua_test/scripts/auth/AuthService.lua:20  
client [127.0.0.1:61706] leave
20200217 12:57:45 ErrorF:\Projects\unity\Moba\Server\lua_wrapper\lua_wrapper.cpp:62  
[LUA ERROR] function refid '1' does not reference a Lua function
20200217 13:00:52 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:31  
Auth server [tcp] listen at: 	8000
20200217 13:01:52 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:31  
Auth server [tcp] listen at: 	8000
20200217 13:01:52 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:37  
register Auth Service:[1] service success
20200217 13:01:52 Debug../../apps/lua_test/scripts/datebase/mysql_auth_center.lua:19  
connect to auth_center_db success
20200217 13:02:09 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:28  
new client come [127.0.0.1:61803]
20200217 13:03:13 Debug../../apps/lua_test/scripts/auth/AuthService.lua:20  
client [127.0.0.1:61803] leave
20200217 13:03:20 ErrorF:\Projects\unity\Moba\Server\lua_wrapper\lua_wrapper.cpp:62  
[LUA ERROR] function refid '1' does not reference a Lua function
20200217 13:08:47 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:31  
Auth server [tcp] listen at: 	8000
20200217 13:08:47 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:37  
register Auth Service:[1] service success
20200217 13:08:47 Debug../../apps/lua_test/scripts/datebase/mysql_auth_center.lua:19  
connect to auth_center_db success
20200217 13:09:03 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:28  
new client come [127.0.0.1:61907]
20200217 13:09:17 DebugF:\Projects\unity\Moba\Server\netbus\Netbus.cpp:237  
client command!!
20200217 13:09:17 ErrorF:\Projects\unity\Moba\Server\netbus\protocol\CmdPackageProtocol.cpp:175  
获取Message类型为空, cmdType: 1, messageName: 
20200217 13:09:17 Debug../../apps/lua_test/scripts/auth/AuthService.lua:20  
client [127.0.0.1:61907] leave
20200217 13:09:18 ErrorF:\Projects\unity\Moba\Server\lua_wrapper\lua_wrapper.cpp:62  
[LUA ERROR] function refid '1' does not reference a Lua function
20200217 13:15:22 DebugF:\Projects\unity\Moba\Server\netbus\protocol\CmdPackageProtocol.cpp:75  
加载：LoginProtocol.proto
20200217 13:15:22 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:31  
Auth server [tcp] listen at: 	8000
20200217 13:15:22 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:37  
register Auth Service:[1] service success
20200217 13:15:22 Debug../../apps/lua_test/scripts/datebase/mysql_auth_center.lua:19  
connect to auth_center_db success
20200217 13:17:20 DebugF:\Projects\unity\Moba\Server\netbus\protocol\CmdPackageProtocol.cpp:75  
加载：LoginProtocol.proto
20200217 13:17:20 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:31  
Auth server [tcp] listen at: 	8000
20200217 13:17:20 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:37  
register Auth Service:[1] service success
20200217 13:17:20 Debug../../apps/lua_test/scripts/datebase/mysql_auth_center.lua:19  
connect to auth_center_db success
20200217 13:18:52 DebugF:\Projects\unity\Moba\Server\netbus\protocol\CmdPackageProtocol.cpp:75  
加载：LoginProtocol.proto
20200217 13:18:52 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:10  
flag 1
20200217 13:18:52 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:14  
flag 2
20200217 13:18:52 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:36  
Auth server [tcp] listen at: 	8000
20200217 13:18:52 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:42  
register Auth Service:[1] service success
20200217 13:18:52 Debug../../apps/lua_test/scripts/datebase/mysql_auth_center.lua:19  
connect to auth_center_db success
20200217 13:20:27 DebugF:\Projects\unity\Moba\Server\netbus\protocol\CmdPackageProtocol.cpp:75  
加载：LoginProtocol.proto
20200217 13:20:27 DebugF:\Projects\unity\Moba\Server\netbus\protocol\CmdPackageProtocol.cpp:93  
注册CmdNameMap: 0 : GuestLoginReq
20200217 13:20:27 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:33  
Auth server [tcp] listen at: 	8000
20200217 13:20:27 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:39  
register Auth Service:[1] service success
20200217 13:20:27 Debug../../apps/lua_test/scripts/datebase/mysql_auth_center.lua:19  
connect to auth_center_db success
20200217 13:21:05 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:30  
new client come [127.0.0.1:62068]
20200217 13:21:19 DebugF:\Projects\unity\Moba\Server\netbus\Netbus.cpp:237  
client command!!
20200217 13:21:19 Debug../../apps/lua_test/scripts/auth/Guest.lua:6  
1	1	1	QwknQNNxk2
20200217 13:21:19 ErrorF:\Projects\unity\Moba\Server\lua_wrapper\lua_wrapper.cpp:98  
[LUA ERROR] ../../apps/lua_test/scripts/auth/Guest.lua:27: attempt to index a nil value (local 'uinfo')
20200217 13:21:19 ErrorF:\Projects\unity\Moba\Server\lua_wrapper\lua_wrapper.cpp:98  
[LUA ERROR] ../../apps/lua_test/scripts/auth/Guest.lua:22: attempt to call a nil value (global 'login')
20200217 13:46:38 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:33  
Auth server [tcp] listen at: 	8000
20200217 13:46:38 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:39  
register Auth Service:[1] service success
20200217 13:46:38 Debug../../apps/lua_test/scripts/datebase/mysql_auth_center.lua:19  
connect to auth_center_db success
20200217 13:46:51 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:30  
new client come [127.0.0.1:62500]
20200217 13:47:02 Debug../../apps/lua_test/scripts/auth/Guest.lua:5  
1	1	1	yLP72ltbjn
20200217 13:47:02 Debug../../apps/lua_test/scripts/auth/Guest.lua:5  
1	1	1	yLP72ltbjn
20200217 13:47:02 Debug../../apps/lua_test/scripts/auth/Guest.lua:31  
this key has been frozen
20200217 13:49:44 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:33  
Auth server [tcp] listen at: 	8000
20200217 13:49:44 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:39  
register Auth Service:[1] service success
20200217 13:49:44 Debug../../apps/lua_test/scripts/datebase/mysql_auth_center.lua:19  
connect to auth_center_db success
20200217 13:49:46 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:30  
new client come [127.0.0.1:62539]
20200217 13:49:59 Debug../../apps/lua_test/scripts/auth/Guest.lua:30  
this key has been frozen
20200217 13:53:04 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:33  
Auth server [tcp] listen at: 	8000
20200217 13:53:04 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:39  
register Auth Service:[1] service success
20200217 13:53:04 Debug../../apps/lua_test/scripts/datebase/mysql_auth_center.lua:19  
connect to auth_center_db success
20200217 13:53:06 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:30  
new client come [127.0.0.1:62571]
20200217 13:53:20 Debug../../apps/lua_test/scripts/datebase/mysql_auth_center.lua:61  
status: 	0
20200217 13:53:20 Debug../../apps/lua_test/scripts/auth/Guest.lua:30  
this key has been frozen
20200217 13:56:41 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:33  
Auth server [tcp] listen at: 	8000
20200217 13:57:16 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:33  
Auth server [tcp] listen at: 	8000
20200217 13:57:16 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:39  
register Auth Service:[1] service success
20200217 13:57:16 Debug../../apps/lua_test/scripts/datebase/mysql_auth_center.lua:19  
connect to auth_center_db success
20200217 13:57:27 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:30  
new client come [127.0.0.1:62650]
20200217 13:57:38 Debug../../apps/lua_test/scripts/datebase/mysql_auth_center.lua:61  
status: 	0
20200217 13:57:38 Debug../../apps/lua_test/scripts/auth/Guest.lua:28  
0
20200217 13:57:38 Debug../../apps/lua_test/scripts/auth/Guest.lua:31  
this key has been frozen
20200217 14:00:03 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:33  
Auth server [tcp] listen at: 	8000
20200217 14:00:03 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:39  
register Auth Service:[1] service success
20200217 14:00:03 Debug../../apps/lua_test/scripts/datebase/mysql_auth_center.lua:19  
connect to auth_center_db success
20200217 14:00:03 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:30  
new client come [127.0.0.1:62681]
20200217 14:00:12 Debug../../apps/lua_test/scripts/datebase/mysql_auth_center.lua:61  
status: 	0
20200217 14:00:12 Debug../../apps/lua_test/scripts/auth/Guest.lua:28  
0
20200217 14:00:12 ErrorF:\Projects\unity\Moba\Server\lua_wrapper\lua_wrapper.cpp:98  
[LUA ERROR] ../../apps/lua_test/scripts/auth/Guest.lua:29: attempt to compare number with string
20200217 17:03:15 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:33  
Auth server [tcp] listen at: 	8000
20200217 17:03:15 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:39  
register Auth Service:[1] service success
20200217 17:03:16 Debug../../apps/lua_test/scripts/datebase/mysql_auth_center.lua:19  
connect to auth_center_db success
20200217 17:03:16 DebugF:\Projects\unity\Moba\Server\apps\lua_test\TestLua.cpp:66  
服务器退出
20200217 17:05:02 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:33  
Auth server [tcp] listen at: 	8000
20200217 17:05:02 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:39  
register Auth Service:[1] service success
20200217 17:05:02 Debug../../apps/lua_test/scripts/datebase/mysql_auth_center.lua:19  
connect to auth_center_db success
20200217 17:05:02 DebugF:\Projects\unity\Moba\Server\apps\lua_test\TestLua.cpp:66  
服务器退出
20200217 17:09:10 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:33  
Auth server [tcp] listen at: 	8000
20200217 17:09:10 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:39  
register Auth Service:[1] service success
20200217 17:09:10 Debug../../apps/lua_test/scripts/datebase/mysql_auth_center.lua:19  
connect to auth_center_db success
20200217 17:09:10 DebugF:\Projects\unity\Moba\Server\apps\lua_test\TestLua.cpp:66  
服务器退出
20200217 17:18:03 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:33  
Auth server [tcp] listen at: 	8000
20200217 17:18:03 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:39  
register Auth Service:[1] service success
20200217 17:18:03 Debug../../apps/lua_test/scripts/datebase/mysql_auth_center.lua:19  
connect to auth_center_db success
20200217 17:18:03 DebugF:\Projects\unity\Moba\Server\apps\lua_test\TestLua.cpp:66  
服务器退出
20200217 17:19:13 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:33  
Auth server [tcp] listen at: 	8000
20200217 17:19:13 Debug../../apps/lua_test/scripts/auth/auth_server_main.lua:39  
register Auth Service:[1] service success
20200217 17:19:13 Debug../../apps/lua_test/scripts/datebase/mysql_auth_center.lua:19  
connect to auth_center_db success
